paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: 로그인 기능
      parameters:
        - name: login
          in: body
          required: true
          schema:
            properties:
              loginId:
                type: string
                description: 아이디
                example: generalId
              password:
                type: string
                description: 비밀번호
                example: generalPassword
      responses:
        "200":
          description: 로그인 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: array
                example: { "accessToken": "토근값" }


  /auth/logout:
    post:
      tags:
        - Auth
      summary: 로그아웃 기능
      parameters:
        - name: logout
          in: body
          required: true
          schema:
            properties:
              userId:
                type: integer
                description: 유저 ID
                example: 1
      responses:
        "200":
          description: 로그아웃 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: string
                example: "성공적으로 로그아웃 되었습니다."
