paths: 
  /brand:
    post:
      tags:
        - Brand
      summary: 브랜드 등록
      parameters:
        - name: createBrand
          in: body
          required: true
          schema:
            properties:
                region_id:
                  type: integer
                  description: 지역 id
                  example: 1
                user_id:
                  type: integer
                  description: 회원 id
                  example: 1
                name:
                  type: string
                  description: 브랜드명
                  example: lodge
                brand_url:
                  type: string
                  description: 브랜드 url
                  example: https://example.com
                description:
                  type: string
                  description: 브랜드 설명
                  example: This is an example brand description.
                brand_image:
                  type: string
                  description: 대표 이미지
                  example: https://example.com/image.png
                business_name:
                  type: string
                  description: 사업자명
                  example: Example Business
                business_registration_number:
                  type: integer
                  description: 사업자 등록번호
                  example: 123456
                contact:
                  type: string
                  description: 담당자 연락처
                  example: example@example.com
      responses:
        "201":
          description: 브랜드 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 201
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: Brand registered successfully
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: lodge
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다
        "500":
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.

  /brand/{id}:
    patch:
      tags:
        - Brand
      summary: 브랜드 정보 수정
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
        - name: updateBrand
          in: body
          required: true
          schema:
            properties:
                name:
                  type: string
                  description: 브랜드명
                  example: updatedExample444
                region_id:
                  type: integer
                  description: 지역 id
                  example: 1
                brand_url:
                  type: string
                  description: 브랜드 URL
                  example: https://example.com
                description:
                  type: string
                  description: 브랜드 설명
                  example: This is an example brand description.
                brand_image:
                  type: string
                  description: 브랜드 이미지
                  example: https://example.com/image.png
                business_name:
                  type: string
                  description: 사업자명
                  example: Example Business
                business_registration_number:
                  type: integer
                  description: 사업자등록번호
                  example: 1111111111
                contact:
                  type: string
                  description: 담당처 연락처
                  example: example@example.com
      responses:
        200:
          description: 브랜드 정보 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: Brand information updated successfully
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      email:
                        type: string
                        example: user@example.com
        400:
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다
        500:
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.

  /brand/{brandId}:
    get:
      tags:
        - Brand
      summary: 브랜드 정보 조회
      description: |
        브랜드 프로필의 브랜드 정보를 제공합니다. 
        brandId = 브랜드id
      parameters:
        - name: brandId
          in: path
          type: integer
          schema:
            type: integer
            description: 브랜드 id
          required: true
      responses:
        '200':
          description: 브랜드 정보 조회 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "SUCCESS!"
              result:
                type: array
                example: {
                  "brand": {
                    "brand_id": 0,
                    "region_name": "서울",
                    "brand_name": "브랜드명",
                    "description": "브랜드 설명",
                    "brand_url": "https://brand.com",
                    "brand_image": "https://image.com"
                  }
                }
        '400':
          description: 파라미터 오류 (존재하지 않는 id값)
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: BRAND4001
              message:
                type: string
                example: 존재하지 않는 브랜드입니다. 
  /brand/{brandId}/products:
    get:
      tags:
        - Brand
      summary: 브랜드 제품 갤러리(목록) 조회
      description: |
        브랜드 제품 갤러리의 제품 목록을 제공합니다. 
        brandId=브랜드id (필수O), 
        page=보려는 페이지 (필수O, 1부터 시작), 
        sort=정렬 방식 (필수X, 숫자, 없으면 조회순, 1: 가격 낮음, 2: 가격 높음, 3: 인기순)
      parameters:
        - name: brandId
          type: integer
          in: path
          schema:
            type: integer
            description: 브랜드 id
          required: true
        - name: page
          type: integer
          in: query
          schema:
            type: integer
            description: 페이지
            example: 1
          required: true
        - name: sort
          type: integer
          in: query
          schema:
            type: integer
            description: 정렬 순서  1 -가격 낮음 2 -가격 높음 3 -인기순 
          required: false
      responses:
        '200':
          description: 브랜드 제품 갤러리(목록) 조회 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "SUCCESS!"
              result:
                type: array
                example: {
                  "products": [
                    {
                      "product_id": 0,
                      "subregion_name": "성수",
                      "brand_name": "브랜드명",
                      "product_name": "상품명",
                      "discount_rate": 10,
                      "price": 1200,
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "product_id": 1,
                      "subregion_name": "성수",
                      "brand_name": "브랜드명",
                      "product_name": "상품명",
                      "discount_rate": 5,
                      "price": 1300,
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "product_id": 6,
                      "subregion_name": "성수",
                      "brand_name": "브랜드명",
                      "product_name": "상품명",
                      "discount_rate": 5,
                      "price": 1600,
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "product_id": 3,
                      "subregion_name": "성수",
                      "brand_name": "브랜드명",
                      "product_name": "상품명",
                      "discount_rate": 10,
                      "price": 1800,
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "product_id": 9,
                      "subregion_name": "성수",
                      "brand_name": "브랜드명",
                      "product_name": "상품명",
                      "discount_rate": 50,
                      "price": 2000,
                      "thumbnail_url": "https://image.png"
                    },
                    {
                      "product_id": 8,
                      "subregion_name": "성수",
                      "brand_name": "브랜드명",
                      "product_name": "상품명",
                      "discount_rate": 40,
                      "price": 2100,
                      "thumbnail_url": "https://image.png"
                    }
                  ],
                  "currentPage": 1,
                  "totalPage": 1
                }
        '400':
          description: 파라미터 오류 (존재하지 않는 id값)
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: BRAND4001
              message:
                type: string
                example: 존재하지 않는 브랜드입니다.
