paths:
  /comments/{postId}/posts:
    get:
      tags:
        - Comment
      summary: 댓글 및 대댓글 일괄 조회
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            description: The ID of the post
      responses:
        200:
          description: 댓글과 대댓글이 조회되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "SUCCESS!"
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        postId:
                          type: integer
                          example: 1
                        userId:
                          type: integer
                          example: 1
                        content:
                          type: string
                          example: "This is a comment."
                        createdDate:
                          type: string
                          format: date
                          example: "2024-08-10"
                        parentId:
                          type: integer
                          example: null
                        children:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              postId:
                                type: integer
                              userId:
                                type: integer
                              content:
                                type: string
                              createdDate:
                                type: string
                                format: date
                              parentId:
                                type: integer
                                example: 1
                              children:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    postId:
                                      type: integer
                                    userId:
                                      type: integer
                                    content:
                                      type: string
                                    createdDate:
                                      type: string
                                      format: date
                                    parentId:
                                      type: integer

        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Bad request"

    post:
      tags:
        - Comment
      summary: 댓글 작성
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            description: The ID of the post
        - name: createComment
          in: body
          required: true
          schema:
            properties:
              parentId:
                type: integer
                description: 부모 댓글
                example: 1
              content:
                type: string
                description: Comment content
                example: "This is a new comment."

      responses:
        201:
          description: 댓글 또는 대댓글 작성이 완료되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 201
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "Comment added successfully"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Bad request"

    delete:
      tags:
        - Comment
      summary: 댓글 또는 대댓글 삭제 (다중 삭제 기능 제공)
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            description: The ID of the post
        - name: ids
          in: query
          required: false
          schema:
            type: string
            description: 삭제할 댓글의 id값을 입력하세요.
            example: "1,2,3"

      responses:
        200:
          description: 선택한 댓글이 모두 삭제되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "Comments deleted successfully"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Bad request"
