paths:
  /order/create:
    post:
      summary: "주문 생성"
      description: "사용자가 장바구니에 담은 상품을 주문합니다."
      tags:
        - Order
      parameters:
        - in: body
          name: order
          description: "주문 정보"
          required: true
          schema:
            type: object
            properties:
              receiver:
                type: string
                example: "홍길동"
                description: "수취인 이름"
              address_name:
                type: string
                example: "자택"
                description: "주소 명칭"
              phone:
                type: string
                example: "010-1234-5678"
                description: "수취인 연락처"
              zip_code:
                type: string
                example: "12345"
                description: "우편번호"
              address:
                type: string
                example: "서울특별시 강남구 테헤란로 123"
                description: "수취인 주소"
              spec_address:
                type: string
                example: "101호"
                description: "상세 주소"
              delivery_fee:
                type: integer
                example: 3000
                description: "배송비"
              total_price:
                type: integer
                example: 50000
                description: "총 주문 금액"
              order_items:
                type: array
                items:
                  type: object
                  properties:
                    product_id:
                      type: integer
                      example: 1
                      description: "상품 ID"
                    product_option_id:
                      type: integer
                      example: 101
                      description: "상품 옵션 ID"
                    price:
                      type: integer
                      example: 25000
                      description: "상품 가격"
                    quantity:
                      type: integer
                      example: 2
                      description: "주문 수량"
      responses:
        200:
          description: "주문 생성 성공"
          schema:
            type: object
            properties:
              order_id:
                type: integer
                example: 9876
                description: "생성된 주문 ID"
              message:
                type: string
                example: "주문이 성공적으로 생성되었습니다."
        400:
          description: "주문 생성 실패"
          schema:
            type: object
            properties:
              message:
                type: string
                example: "유효하지 않은 요청입니다."

  /order/validate:
    post:
      summary: "주문 검증"
      description: "사용자가 결제 후 주문이 성공적으로 처리되었는지 검증합니다."
      tags:
        - Order
      parameters:
        - in: body
          name: order
          description: "주문 검증 정보"
          required: true
          schema:
            type: object
            properties:
              order_id:
                type: integer
                example: 9876
                description: "주문 ID"
              imp_uid:
                type: string
                example: "imp_123456789"
                description: "아임포트 결제 고유 ID"
      responses:
        200:
          description: "주문 검증 성공"
          schema:
            type: object
            properties:
              status:
                type: string
                example: "COMPLETE"
                description: "주문 상태"
              message:
                type: string
                example: "주문이 성공적으로 처리되었습니다."
        400:
          description: "주문 검증 실패"
          schema:
            type: object
            properties:
              message:
                type: string
                example: "유효하지 않은 주문 ID 또는 결제 정보입니다."

  /order/cancel:
    post:
      summary: "주문 취소"
      description: "사용자가 결제된 주문을 취소합니다."
      tags:
        - Order
      parameters:
        - in: body
          name: cancelRequest
          description: "주문 취소 정보"
          required: true
          schema:
            type: object
            properties:
              order_id:
                type: integer
                example: 9876
                description: "주문 ID"
              reason:
                type: string
                example: "고객 요청에 의한 취소"
                description: "취소 사유"
      responses:
        200:
          description: "주문 취소 성공"
          schema:
            type: object
            properties:
              message:
                type: string
                example: "주문이 성공적으로 취소되었습니다."
        400:
          description: "주문 취소 실패"
          schema:
            type: object
            properties:
              message:
                type: string
                example: "유효하지 않은 주문 ID입니다."