paths:
  /reviews/{oiId}:
    get:
      tags:
        - Review
      summary: 리뷰 조회
      parameters:
        - name: oiId
          type: integer
          in: path
          schema:
            type: integer
            description: 주문 아이템 PK
            example: 1
          required: true
      responses:
        "200":
          description: 리뷰 조회 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "SUCCESS!"
              result:
                type: array
                example:
                  {
                    "review":
                      {
                        "id": 1,
                        "user_id": 1,
                        "product_id": 1,
                        "oi_id": 1,
                        "content": "리뷰 조회 내용",
                        "rating": 5,
                        "created_at": "2024-08-06T04:35:56.000Z",
                      },
                    "image":
                      {
                        "id": 1,
                        "review_id": 1,
                        "filename": "reviews%2F42c5bf2c0b0d907da1acdd11b39bee71_%ED%95%98%EC%9A%B8.jpg",
                        "created_at": "2024-08-06T04:35:56.000Z",
                        "updated_at": "2024-08-06T04:35:56.000Z",
                      },
                  }
  /reviews:
    post:
      tags:
        - Review
      summary: 리뷰 작성
      consumes:
        - multipart/form-data
      parameters:
        - in: query
          name: directory
          schema:
            type: string
            example: reviews
        - in: formData
          name: image
          type: array
          items:
            type: file
            format: binary
            description: 파일 업로드 (최소 0개, 최대 2개)
        - in: formData
          name: product_id
          schema:
            type: integer
            description: 상품 PK
            example: 1
          required: true
        - in: formData
          name: oi_id
          schema:
            type: integer
            description: 주문 항목 PK
            example: 1
          required: true
        - in: formData
          name: content
          schema:
            type: string
            description: 내용
            example: 리뷰 작성 내용
        - in: formData
          name: rating
          schema:
            type: integer
            description: 평점
            example: 5
      responses:
        "200":
          description: 리뷰 작성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "SUCCESS!"
                  result:
                    type: object
                    properties:
                      review:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            user_id:
                              type: integer
                              example: 1
                            product_id:
                              type: integer
                              example: 1
                            oi_id:
                              type: integer
                              example: 1
                            content:
                              type: string
                              example: 리뷰 작성 내용
                            rating:
                              type: integer
                              example: 5
                            created_at:
                              type: string
                              format: timestamp
                              example: "2024-08-06T03:11:41.000Z"

  /reviews/{reviewId}:
    patch:
      tags:
        - Review
      summary: 리뷰 수정
      consumes:
        - multipart/form-data
      parameters:
        - in: path
          name: reviewId
          schema:
            type: integer
            description: 리뷰 PK
            example: 1
          required: true
        - in: query
          name: directory
          schema:
            type: string
            example: reviews
        - in: formData
          name: image
          type: array
          items:
            type: file
            format: binary
            description: 파일 업로드 (최소 0개, 최대 2개)
        - in: formData
          name: content
          schema:
            type: string
            description: 내용
            example: 수정 텍스트
        - in: formData
          name: rating
          schema:
            type: integer
            description: 평점
            example: 4
      responses:
        "200":
          description: 리뷰 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "SUCCESS!"
                  result:
                    type: object
                    properties:
                      review:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 3
                            user_id:
                              type: integer
                              example: 1
                            product_id:
                              type: integer
                              example: 1
                            oi_id:
                              type: integer
                              example: 5
                            content:
                              type: string
                              example: "수정 텍스트"
                            rating:
                              type: integer
                              example: 3
                            created_at:
                              type: string
                              format: date-time
                              example: "2024-08-06T03:11:41.000Z"
    delete:
      tags:
        - Review
      summary: 리뷰 삭제
      parameters:
        - name: reviewId
          type: integer
          in: path
          schema:
            type: integer
            description: 리뷰 PK
            example: 1
          required: true
      responses:
        "200":
          description: 리뷰 삭제 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "SUCCESS!"
              result:
                type: string
                example: "리뷰가 성공적으로 삭제되었습니다."
          "400":
            description: 파라미터 오류
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: string
                  example: REVIEW4001
                message:
                  type: string
                  example: 존재하지 않는 리뷰입니다.